=== JoshuaLobo/WebTechLab/xml/simple.dtd
<!ELEMENT hero (info) >
<!ELEMENT info (name, brief_intro, age, list_of_abilities, item)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT brief_intro (#PCDATA)>
<!ELEMENT age (#PCDATA)>
<!ELEMENT list_of_abilities (#PCDATA)>
<!ELEMENT item (name, details_info)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT details_info (#PCDATA)>

=== JoshuaLobo/WebTechLab/xml/ExternalXML_DTD.xml
<?xml version="1.0"?>

<!DOCTYPE list SYSTEM "simple.dtd">
<hero>
  <info>
    <name>Angela Ziegler</name>
     		<brief_intro>Mercy's Valkyrie suit helps keep her close to teammates like a guardian angel;healing, resurrecting or strengthening them with the beams emanating from her Caduceus Staff.</brief_intro>
   		    <age>37</age>
        <list_of_abilities>
    		  <item>
		        <name>1. CADUCEUS STAFF</name>
	     		   <details_info>Mercy engages one of two beams that connect to an ally. By maintaining the beams, she can either restore that allay's health or increase the amount of damage they deal.</details_info>
	      </item>
        
	      <item>
     			   <name>2. CADUCEUS BLASTER</name>
		        <details_info>Mercy shoots a round from her sidearm.</details_info>
	      </item>

	      <item>
		        <name>3.GUARDIAN ANGEL</name>
		        <details_info>Mercy flies towards a targerted allay, allowing her to reach them quickly and provide assitance in crucial moments.</details_info>
	      </item>

     		 <item>
		        <name>4.RESURRECT</name>
		        <details_info>Mercy brings a dead ally back into the fight with full health.</details_info>
	      </item>

     		 <item>
		        <name>5. ANGELIC DESCENT</name>
		        <details_info>Propelled by her Valkyrie suit, Mercy slows the speed of her descent from great heights.</details_info>
	      </item>

     		 <item>
		        <name>6. VALKYRIE</name>
		        <details_info>Gain the ability to fly.Mercy's abilities are enhanced.</details_info>
	      </item>

        </list_of_abilities>
  </info>
 </hero>
